### ISSUE TITLE
After installing update 1.1.0 and reinstall i receive exception on startup

### ISSUE THREAD

**Issue by JSCProjects** [Particular/ServiceControl.Monitoring#102]
Hi,

After installing update/reinstall 1.1.0 I receive on startup 
![image](https://user-images.githubusercontent.com/19533149/35084761-c8a5fbda-fc25-11e7-9e36-6f7a345351fc.png)

Service cannot be started. System.Exception: Azure Service Bus transport requires a topology to be specified. Use `.UseTopology<ITopology>()` configuration API to specify topology to use.
   at NServiceBus.AzureServiceBusTransport.GetConfiguredTopology(SettingsHolder settings)
   at NServiceBus.AzureServiceBusTransport.Initialize(SettingsHolder settings, String connectionString)
   at ServiceControl.Transports.AzureServiceBus.ForwardingTopologyAzureServiceBusTransport.Initialize(SettingsHolder settings, String connectionString)
   at NServiceBus.InitializableEndpoint.<Initialize>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Endpoint.<Start>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.T...

**Comment by danielmarbach** [comment]
Thanks for reporting. This was probably introduced by https://github.com/Particular/ServiceControl.Monitoring/pull/99. We'll check

**Comment by Scooletz** [comment]
@JSCProjects We confirmed that it has been introduced by #99 . I'm starting working on it. We should release a package within few hours. I'll be updating this issue.

**Comment by tmasternak** [comment]
@JSCProjects the patch is out. Feel free to close this issue when it's verified.
