### ISSUE TITLE
Monitoring view still shows error message count, but messages are already fixed

### ISSUE THREAD

**Issue by JSCProjects** [Particular/ServiceControl.Monitoring#115]
Screenshot says more than words ;-) I know a restart of the monitoring service can fix this, but my colleague doesn't want to do that every time and it doesn't work all the time

![image](https://user-images.githubusercontent.com/19533149/38659427-cbf0a042-3e29-11e8-94a7-ac522acbfbaa.png)

**Comment by WilliamBZA** [comment]
We are actively working on this, but it's a major change so I unfortunately don't have an ETA for you on when this will be resolved. The largest component of the work is data migration which is where we're currently focusing our solution efforts.

**Comment by WilliamBZA** [comment]
@JSCProjects When you say "a restart of the monitoring service can fix this", are you seeing the numbers match up if you restart _ONLY_ the monitoring instance of ServiceControl? Or do you also have to restart the main instance of ServiceControl too? What about a page refresh?

**Comment by WilliamBZA** [comment]
@JSCProjects Here's a very early alpha that should help with this. Please give it a try and see if it improves the situation a bit.

https://drive.google.com/open?id=1OWjML6EwNYyH3Ha0g30SQV49BiT_hU-7

**Comment by JSCProjects** [comment]
@WilliamBZA to backup and restore this page is still ok?
https://docs.particular.net/servicecontrol/backup-sc-database

**Comment by WilliamBZA** [comment]
Yes, still correct

**Comment by JSCProjects** [comment]
@WilliamBZA when upgrading I'm receiving this error:
System.ComponentModel.Win32Exception (0x80004005): The parameter is incorrect
   at ServiceControlInstaller.Engine.UrlAcl.UrlReservation.reserveURL(String networkURL, String securityDescriptor) in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControlInstaller.Engine\UrlAcl\UrlReservation.cs:line 226
   at ServiceControlInstaller.Engine.Instances.ServiceControlInstance.RecreateUrlAcl(ServiceControlInstance oldSettings) in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControlInstaller.Engine\Instances\ServiceControlInstance.cs:line 286
   at ServiceControlInstaller.Engine.Instances.ServiceControlInstance.ApplyConfigChange() in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControlInstaller.Engine\Instances\ServiceControlInstance.cs:line 213
   at ServiceControlInstaller.Engine.Instances.ServiceControlUpgradeOptions.ApplyChangesToInstance(ServiceControlInstance instance) in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControlInstaller.Engine\Instances\ServiceControlUpgradeOptions.cs:line 33
   at ServiceControl.Config.Framework.Modules.ServiceControlInstanceInstaller.Upgrade(String instanceName, ServiceControlUpgradeOptions upgradeOptions, IProgress`1 progress) in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl.Config\Framework\Modules\InstallerModule.cs:line 106
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ServiceControl.Config.Commands.UpgradeServiceControlInstanceCommand.<ExecuteAsync>d__5.MoveNext() in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl.Config\Commands\UpgradeServiceControlInstanceCommand.cs:line 196
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ServiceControl.Config.Framework.Commands.AwaitableAbstractCommand`1.<ServiceControl-Config-Framework-Commands-ICommand<T>-Execute>d__3.MoveNext() in C:\BuildAgent\work\7189a56f9f44affc\src\ServiceControl.Config\Framework\Commands\AwaitableAbstractCommand.cs:line 24
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by JSCProjects** [comment]
I also lost my monitoring instance :-(

**Comment by WilliamBZA** [comment]
You can bypass that by changing the Hostname to `localhost`, run the upgrade, and then change the hostname back to the previous value (I assume `*`)

**Comment by WilliamBZA** [comment]
> I also lost my monitoring instance

That's very strange, there hasn't been any code changes to the monitoring portion.

Is the instance still registered in `HKLM/System/CurrentControlSet/Services`?

**Comment by JSCProjects** [comment]
nope it's gone. FYI Im hosting multiple servicecontrol & monitoring instances on this vm

**Comment by WilliamBZA** [comment]
Do the monitoring instance files still exist?

**Comment by JSCProjects** [comment]
Yup and I can't reconfigure it
![image](https://user-images.githubusercontent.com/19533149/39293087-49ee3aae-4938-11e8-8c91-671b5b1baa90.png)

**Comment by WilliamBZA** [comment]
I think it's best to delete the previous UrlAcl.

`netsh http delete urlacl url=http://vbwmlms898.dm801.local:33633`

I can't come up with any reasonable explanation as to how windows services lost the monitoring instance but kept the files on disk...

**Comment by JSCProjects** [comment]
My DEV environment is done. Will do the same now for TEST

**Comment by JSCProjects** [comment]
@WilliamBZA sorry but it didn't fixed it

![image](https://user-images.githubusercontent.com/19533149/39298177-cbe022e0-4945-11e8-9600-67c69185b70d.png)

**Comment by WilliamBZA** [comment]
The way this screen works is that it first loads the endpoints from the monitoring services. Once it has those, it submits a separate query to ServiceControl to find out if there are any failed messages for any of those endpoints. 

So somehow the query to ServiceControl is showing 9 failed messages for that endpoint, but is not showing them as failed messages in the main window.

If you navigate to the failed messages page and change the categories to show failed messages by endpoint, do the messages show in that list?

**Comment by JSCProjects** [comment]
I changed the categories and saw that there was a dismiss button still present after I pressed that the numbers were OK!

**Comment by WilliamBZA** [comment]
_facepalm_ That makes sense at least.

Whelp, well thanks for running the new version for us at least and giving us feedback. Now we know we have to track down a urlacl bug.

I'm still concerned about the monitoring instance disappearing though.
