### ISSUE TITLE
Graceful shutdown in Queue Length Providers

### ISSUE THREAD

**Issue by tmasternak** [Particular/ServiceControl.Monitoring#152]
For some queue length providers, shutting down the endpoint causes 
> 2018-10-04 12:28:53.5824|41|Error|ServiceControl.Transports.SQLServer.QueueLengthProvider|Error querying sql queue sizes.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ServiceControl.Transports.SQLServer.QueueLengthProvider.<UpdateChunk>d__14.MoveNext() in C:\BuildAgent\work\75ab57c3309c2d4a\src\ServiceControl.Transports.SQLServer\QueueLengthProvider.cs:line 141
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ServiceControl.Transports.SQLServer.QueueLengthProvider.<QueryTableSizes>d__13.MoveNext() in C:\BuildAgent\work\75ab57c3309c2d4a\src\ServiceControl.Transports.SQLServer\QueueLengthProvider.cs:line 130
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ServiceControl.Transports.SQLServer.QueueLengthProvider.<<Start>b__10_0>d.MoveNext() in C:\BuildAgent\work\75ab57c3309c2d4a\src\ServiceControl.Transports.SQLServer\QueueLengthProvider.cs:line 75

to be logged even though this is users action that caused that. We should handle this scenario gracefully.

**Comment by danielmarbach** [comment]
Addressed in #175 . Closing
