### ISSUE TITLE
QueueLengthProvider doesn't work with SQS QueueNamePrefixes and floods the logs

### ISSUE THREAD

**Issue by danielmarbach** [Particular/ServiceControl.Monitoring#165]
QueueNamePrefix with SQS is now officially supported with ServiceControl.Monitoring. The problem is that the queue length provider hasn't been changed to support it as well. So when you enable the QueueNamePrefix like the following screenshot shows

![image](https://user-images.githubusercontent.com/174258/48932259-32209c00-eefb-11e8-94a5-d1657c70437e.png)

Then the queue length provider doesn't work and floods the logs with

```
2018-11-21 17:14:22.2167|18|Error|ServiceControl.Transports.AmazonSQS.QueueLengthProvider|Obtaining an approximate number of messages failed for ‘GRM-ActivityStream-DataMigration-Host’
Amazon.SQS.Model.QueueDoesNotExistException: The specified queue does not exist for this wsdl version. —> Amazon.Runtime.Internal.HttpErrorResponseException: The remote server returned an error: (400) Bad Request. —> System.Net.WebException: The remote server returned an error: (400) Bad Request.
at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
at System.Threading.Tasks.TaskFactory1.FromAsyncCoreLogic(IAsyncResult iar, Func2 endFunction, Action1 endAction, Task1 promise, Boolean requiresSynchronization)
```

and this at a rate of every 200 ms. In addition to the queue length provider not working it fills the log directory quickly with gigantic log files which can lead to outages due to not enough disk space available.

**Comment by danielmarbach** [comment]
Closed via #164
