### ISSUE TITLE
SC.Monitoring should not require MSDTC and use ReceiveOnly transaction mode

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServiceControl.Monitoring#87]
It seems that SC.Monitoring requires MSDTC.

I did not start my remote MSDTC server in my lab environment and get the following error at startup which seems to indicate that it requires MSDTC. SC.Monitoring transports should operate in ReceiveOnly transaction modes.

```
2017-12-04 15:45:10.4383|4|Warn|NServiceBus.MessagePump|MSMQ receive operation failed
System.Transactions.TransactionAbortedException: The transaction has aborted. ---> System.Transactions.TransactionManagerCommunicationException: Communication with the underlying transaction manager has failed. ---> System.Runtime.InteropServices.COMException: The RPC server is unavailable. (Exception from HRESULT: 0x800706BA)
   at System.Transactions.Oletx.IDtcProxyShimFactory.ConnectToProxy(String nodeName, Guid resourceManagerIdentifier, IntPtr managedIdentifier, Boolean& nodeNameMatches, UInt32& whereaboutsSize, CoTaskMemHandle& whereaboutsBuffer, IResourceManagerShim& resourceManagerShim)
   at System.Transactions.Oletx.DtcTransactionManager.Initialize()
   --- End of inner exception stack trace ---
   at System.Transactions.Oletx.DtcTransactionManager.Initialize()
   at System.Transactions.Oletx.DtcTransactionManager.get_ProxyShimFactory()
   at System.Transactions.Oletx.OletxTransactionManager.CreateTransaction(TransactionOptions properties)
   at System.Transactions.TransactionStatePromoted.EnterState(InternalTransaction tx)
   --- End of inner exception stack trace ---
   at System.Transactions.TransactionStateAborted.CheckForFinishedTransaction(InternalTransaction tx)
   at System.Transactions.EnlistableStates.Promote(InternalTransaction tx)
   at System.Transactions.Transaction.Promote()
   at System.Transactions.TransactionInterop.ConvertToOletxTransaction(Transaction transaction)
   at System.Transactions.TransactionInterop.GetDtcTransaction(Transaction transaction)
   at System.Messaging.MessageQueue.StaleSafeReceiveMessage(UInt32 timeout, Int32 action, MQPROPS properties, NativeOverlapped* overlapped, ReceiveCallback receiveCallback, CursorHandle cursorHandle, IntPtr transaction)
   at System.Messaging.MessageQueue.ReceiveCurrent(TimeSpan timeout, Int32 action, CursorHandle cursor, MessagePropertyFilter filter, MessageQueueTransaction internalTransaction, MessageQueueTransactionType transactionType)
   at System.Messaging.MessageQueue.Receive(TimeSpan timeout, MessageQueueTransactionType transactionType)
   at NServiceBus.ReceiveStrategy.TryReceive(MessageQueueTransactionType transactionType, Message& message)
   at NServiceBus.TransactionScopeStrategy.<ReceiveMessage>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.MessagePump.<>c.<<ReceiveMessage>b__7_0>d.MoveNext()
```

**Comment by ramonsmits** [comment]
Solved by #88
