### ISSUE TITLE
'QueueLengthSnapshotting' occasionally throws on shutdown

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServiceControl.Monitoring#91]
I occasionally see the following exception in the log file. Seems that some task cancellation isn't handled gracefully.

```
2017-12-12 21:31:55.2739|8|Warn|NServiceBus.Features.FeatureStartupTaskController|Exception occurred during stopping of feature startup task 'QueueLengthSnapshotting'.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ServiceControl.Monitoring.QueueLength.QueueLengthSnapshotting.<<OnStart>b__2_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Features.FeatureStartupTaskController.<Stop>d__5.MoveNext()
```

**Comment by Scooletz** [comment]
Is this on the ServiceControl side (thus `ServiceControl.Monitoring`) or the endpoint using `NServiceBus.Metrics.ServiceControl` ?

**Comment by mikeminutillo** [comment]
It's in SC Monitoring. The QueueLengthSnapshotting startup task sends a cancellation token into it's Task.Delay but it doesn't handle it properly. So when we stop and we hand the task back to NSB, it gets a faulted Task.

**Comment by mikeminutillo** [comment]
I raised https://github.com/Particular/ServiceControl.Monitoring/pull/93 to fix it
