### ISSUE TITLE
After deleting the monitoring queue, SC.Monitoring must be reinstalled to recreated the queues

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServiceControl.Monitoring#92]
SC.Monitoring does not start after the queue was not present anymore. In my case because I reinstalled MSMQ. I had to reinstall SC.Monitoring for it to recreate all relevant queues.

```
2017-12-12 22:00:03.9614|4|Fatal|NServiceBus.StartableEndpoint|Receiver Main failed to initialize.
System.InvalidOperationException: There is a problem with the input inputQueue: FormatName:DIRECT=OS:ZOLDER\private$\Particular.Monitoring. See the enclosed exception for details. ---> System.Messaging.MessageQueueException: The queue does not exist or you do not have sufficient permissions to perform the operation.
   at System.Messaging.MessageQueue.MQCacheableInfo.get_Transactional()
   at System.Messaging.MessageQueue.get_Transactional()
   at NServiceBus.MessagePump.QueueIsTransactional()
   --- End of inner exception stack trace ---
   at NServiceBus.MessagePump.QueueIsTransactional()
   at NServiceBus.MessagePump.Init(Func`2 onMessage, Func`2 onError, CriticalError criticalError, PushSettings settings)
   at NServiceBus.TransportReceiver.Init()
   at NServiceBus.StartableEndpoint.<InitializeReceivers>d__3.MoveNext()
```

**Comment by seanfarmar** [comment]
Same for SC
